### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by rolfschr** [drseb/hpo-db-version#1]
Hi,

I tried to compile the software but could not manage to run it. I have no experience with maven, so please forgive my ignorance.

```
$ mvn package
...
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.964 s
[INFO] Finished at: 2019-02-27T15:34:44+01:00
[INFO] ------------------------------------------------------------------------
```

```
# 1st try
$ java -cp ./target/hpo-db-version-0.0.1-SNAPSHOT.jar  de.phenomics.database.CreateMysqlHPODbVersion
java.lang.NoClassDefFoundError: org/apache/commons/cli/CommandLineParser
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.privateGetMethodRecursive(Unknown Source)
        at java.lang.Class.getMethod0(Unknown Source)
        at java.lang.Class.getMethod(Unknown Source)
        at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.cli.CommandLineParser
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 7 more
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" %                                                                                                                                                                                    

# 2nd try
$ java -jar ./target/hpo-db-version-0.0.1-SNAPSHOT.jar
no main manifest attribute, in ./target/hpo-db-version-0.0.1-SNAPSHOT.jar

# 3rd try
$ java -jar ./target/hpo-db-version-0.0.1-SNAPSHOT.jar main
no main manifest attribute, in ./target/hpo-db-version-0.0.1-SNAPSHOT.jar
```

**Comment by gcurrier** [comment]
You'll need to add some plugins to the "build" section of the pom so that maven knows how to package it (with a manifest) and the dependent jars

EDIT:

I got it to work using these additional plugins:

```
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                      http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>
  <groupId>hpo-db-version</groupId>
  <artifactId>hpo-db-version</artifactId>
  <version>0.0.1-SNAPSHOT</version>

  <properties>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
  </properties>
  <build>
    <plugins>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.0</version>
        <configuration>
          <source>${maven.compiler.source}</source>
          <target>${maven.compiler.source}</target>
        </configuration>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <version>3.1.0</version>
        <configuration>
          <archive>
            <manifest>
              <addClasspath>true</addClasspath>
              <classpathPrefix>lib/</classpathPrefix>
              <mainClass>de.phenomics.database.CreateMysqlHPODbVersion</mainClass>
            </manifest>
          </archive>
        </configuration>
      </plugin>

      <plugin>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-shade-plugin</artifactId>
      <version>3.1.1</version>
        <configuration>
          <transformers>
            <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
              <mainClass>de.phenomics.database.CreateMysqlHPODbVersion</mainClass>
            </transformer>
          </transformers>
        </configuration>
      <executions>
        <execution>
          <phase>package</phase>
          <goals>
            <goal>shade</goal>
          </goals>
        </execution>
      </executions>
    </plugin>

    </plugins>
  </build>

  <!--<repositories>-->
    <!--<repository>-->
      <!--<id>compbio</id>-->
      <!--<url>http://compbio.charite.de/tl_files/maven</url>-->
    <!--</repository>-->
  <!--</repositories>-->

  <dependencies>

    <dependency>
      <groupId>commons-lang</groupId>
      <artifactId>commons-lang</artifactId>
      <version>2.1</version>
    </dependency>

    <dependency>
      <groupId>org.codehaus.plexus</groupId>
      <artifactId>plexus-utils</artifactId>
      <version>1.1</version>
    </dependency>

    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <version>23.0</version>
    </dependency>

    <dependency>
      <groupId>commons-cli</groupId>
      <artifactId>commons-cli</artifactId>
      <version>1.4</version>
    </dependency>

    <dependency>
      <groupId>mysql</groupId>
      <artifactId>mysql-connector-java</artifactId>
      <version>8.0.15</version>
    </dependency>

    <dependency>
      <groupId>phenologizer</groupId>
      <artifactId>phenologizer</artifactId>
      <version>0.0.4-SNAPSHOT</version>
    </dependency>

    <dependency>
      <groupId>javautil_pheno</groupId>
      <artifactId>javautil_pheno</artifactId>
      <version>0.0.3-SNAPSHOT</version>
    </dependency>

  </dependencies>

</project>
```

Compile with 
```
mvn clean package
```

then running it 
```
java -jar hpo-db-version-0.0.1-SNAPSHOT.jar (your params here)
```

I am using Maven 3.6.0 for the build
